extends: airbnb
parser: babel-eslint
env:
  es6: true
  node: true
  mocha: true
rules:
  global-require: 0
  func-names: 0
  no-param-reassign: 0
  arrow-body-style: 0
  max-len: 0
  dot-notation: 0
  no-underscore-dangle: 0
